### ISSUE TITLE
Always receive "stream terminated by RST_STREAM with error code: STREAM_CLOSED" after grpc request

### ISSUE THREAD

**Issue by ray2011** [tsloughter/grpcbox#51] opened 2021-02-24 07:13 UTC
When go grpc client or grpcbox client call gopcbox server, both see RST_STREAM in tcpdump log:

go client call:
![image](https://user-images.githubusercontent.com/7893714/108960912-979efc80-76b1-11eb-8866-d26cf989add1.png)

grpcbox client call:
![image](https://user-images.githubusercontent.com/7893714/108960991-b4d3cb00-76b1-11eb-81d7-7647a6e3fbf5.png)

RST_STREAM detail:
![image](https://user-images.githubusercontent.com/7893714/108961082-cfa63f80-76b1-11eb-9f00-b8ce38af5518.png)

when go grpc client or grpcbox client call go grpc server, not see RST_STREAM in tcpdump log:

go grpc call:
![image](https://user-images.githubusercontent.com/7893714/108961208-f795a300-76b1-11eb-91c1-9bd56a7061b6.png)

grpcbox call:
![image](https://user-images.githubusercontent.com/7893714/108961291-15630800-76b2-11eb-8358-9731f499bd00.png)

go grpc client don't handle RST_STREAM, it will return an error, but grpcbox won't.

go error: 
![image](https://user-images.githubusercontent.com/7893714/108961656-9fab6c00-76b2-11eb-95c9-045ceef594f3.png)

grpcbox result:
![image](https://user-images.githubusercontent.com/7893714/108961697-ae921e80-76b2-11eb-9601-71ce17dd483b.png)

My issue is:  why RST_STREAM happened after the grpc response send?

**Comment by RaynorGu** [comment] 2021-02-24 07:14
rebar.config :
![image](https://user-images.githubusercontent.com/7893714/108961859-e4cf9e00-76b2-11eb-981d-19c01b459c79.png)

sys.config:
![image](https://user-images.githubusercontent.com/7893714/108961880-eef19c80-76b2-11eb-930d-38a0f5d4f0ee.png)

**Comment by fenollp** [comment] 2021-05-03 06:13
Same issue, [here's the (short) code](https://github.com/LesnyRumcajs/grpc_bench/pull/125) and the call:
```
grpcurl  -proto ../proto/helloworld/helloworld.proto -d '{"name":"qweqweqwe"}' -plaintext localhost:50051 helloworld.Greeter/SayHello
```
Note: when running in `rebar3 shell` the first call works as intended but always fails from the 2nd call on.
```
ERROR:
  Code: Internal
  Message: stream terminated by RST_STREAM with error code: STREAM_CLOSED
```
Maybe it only has to do with the way Go terminates the connection as I've tested (and received this message) only with grpcurl and [ghz](https://ghz.sh/)

**Comment by fenollp** [comment] 2021-05-06 20:17
@tsloughter could this be due to the transport being insecure?

**Comment by tsloughter** [comment] 2021-05-31 22:56
I still don't know when I'll have time to investigate and fix this but could I get some more info, like does every request between erlang and go fail? 

And I realize I'm not sure if the issue is the way it is being terminated or if the issue is how grpcbox handles the termination? Like "go grpc client don't handle RST_STREAM, it will return an error, but grpcbox won't.", is this saying Go doesn't handle the RST_STREAM because it shouldn't be sent?

**Comment by RaynorGu** [comment] 2021-06-01 07:42
Is this saying Go doesn't handle the RST_STREAM because it shouldn't be sent? 

Yes. 

#####Errors

When an application or runtime error occurs during an RPC a Status and Status-Message are delivered in Trailers.

In some cases it is possible that the framing of the message stream has become corrupt and the RPC runtime will choose to use an RST_STREAM frame to indicate this state to its peer. RPC runtime implementations should interpret RST_STREAM as immediate full-closure of the stream and should propagate an error up to the calling application layer.

RST_STRWAM means an error, but no error occured.

**Comment by lixen-wg2** [comment] 2021-06-15 12:11
I was able to reproduce the issue with 

```
wget https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.2/grpc_health_probe-linux-amd64

and then runnning it twice 

❯ ./grpc_health_probe-linux-amd64  -addr=localhost:8080
status: SERVING
 ~/Downloads
❯ ./grpc_health_probe-linux-amd64  -addr=localhost:8080
error: health rpc failed: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: STREAM_CLOSED
```

It seems to be this state change in chatterbox that cause the problem. Not sure what the correct change should be or if it is a side effect that I should change instead.
```
--- a/src/h2_stream.erl
+++ b/src/h2_stream.erl
@@ -719,7 +719,7 @@ send_trailers(State, Trailers, Stream=#stream_state{connection=Pid,
     h2_connection:actually_send_trailers(Pid, StreamId, Trailers),
     case State of
         half_closed_remote ->
-            {next_state, closed, Stream};
+            {next_state, half_closed_remote, Stream};
         open ->
             {next_state, half_closed_local, Stream}
     end.
 ```

**Comment by lixen-wg2** [comment] 2021-06-15 13:14
It seems to be introduced in:
https://github.com/tsloughter/chatterbox/commit/e15e56d328f1c4eaa5808861611cca083b9b4cff

**Comment by lixen-wg2** [comment] 2021-06-15 13:54
I was able to reproduce the issue with

```
wget https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.2/grpc_health_probe-linux-amd64

and then runnning it twice

❯ ./grpc_health_probe-linux-amd64  -addr=localhost:8080
status: SERVING
 ~/Downloads
❯ ./grpc_health_probe-linux-amd64  -addr=localhost:8080
error: health rpc failed: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: STREAM_CLOSED
```
and verify that revert of tsloughter/chatterbox@e15e56d solve the issue.

**Comment by shhnwz** [comment] 2021-06-29 11:22
> I was able to reproduce the issue with
> 
> ```
> wget https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.2/grpc_health_probe-linux-amd64
> 
> and then runnning it twice
> 
> ❯ ./grpc_health_probe-linux-amd64  -addr=localhost:8080
> status: SERVING
>  ~/Downloads
> ❯ ./grpc_health_probe-linux-amd64  -addr=localhost:8080
> error: health rpc failed: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: STREAM_CLOSED
> ```
> 
> and verify that revert of [tsloughter/chatterbox@e15e56d](https://github.com/tsloughter/chatterbox/commit/e15e56d) solve the issue.

This Issue gave us nightmare in a pre-production environment.. Thanks for identifying this, we have to revert this commit to move further.

**Comment by tsloughter** [comment] 2021-06-29 13:36
@shhnwz does using https://github.com/tsloughter/chatterbox/pull/7 instead of reverting work for you?

**Comment by lixen-wg2** [comment] 2021-06-30 11:31
@tsloughter we are running with that pr and have not seen any issues so far.

**Comment by lixen-wg2** [comment] 2021-07-06 13:27
That was not true when running with my pr we end up leaking h2_stream procs. Will drop that for now and revert instead.

**Comment by tsloughter** [comment] 2021-07-06 16:25
Maybe just need to stop the process in that event handler you added in the PR?

**Comment by lixen-wg2** [comment] 2021-07-07 06:51
Yes that worked. I was thinking it would end up in the normal flow and stop.

**Comment by tsloughter** [comment] 2021-07-07 12:58
I think that makes more sense. Stream is in closed state, so just stop it.

I wonder if the `RST_STREAM` was meant as a catch all for if there were messages sent to the stream process that weren't understood. The `send_t` is understood so simply matching it and closing is the correct thing to do.... Just trying to think this through. Could use a http2 flow chart :)

**Comment by tsloughter** [comment] 2021-07-07 13:00
If tests pass I'll probably merge this and try to get a release made soon.

**Comment by tsloughter** [comment] 2021-09-04 14:07
So there is a test failure is why this hasn't been merged yet.

I haven't been able to look at it and haven't looked at anything really in months. But I start work again on the 13th and part of that job will involve grpcbox, so I will be digging in with fixes, performance improvements and making releases again finally in the near future.

**Comment by lixen-wg2** [comment] 2021-09-06 07:07
The tests are not failing for me locally but do not know how to rerun them in gh actions.

**Comment by fenollp** [comment] 2022-01-09 21:26
Both PRs fail CI with the same reason.

| PR | CI  |
|-----|---|
|  https://github.com/tsloughter/chatterbox/pull/7   |  https://github.com/fenollp/chatterbox/runs/4754384849?check_suite_focus=true |
|  https://github.com/tsloughter/chatterbox/pull/12   | https://github.com/fenollp/chatterbox/runs/4754378209?check_suite_focus=true  |


```
%%% http2_spec_3_5_SUITE: 
=CRASH REPORT==== 9-Jan-2022::18:08:45.655765 ===
  crasher:
    initial call: chatterbox_ranch_protocol:init/4
    pid: <0.2102.0>
    registered_name: []
    exception exit: invalid_preface
      in function  h2_connection:become/3 (/home/runner/work/chatterbox/chatterbox/src/h2_connection.erl, line 205)
    ancestors: [<0.2082.0>,<0.2081.0>,ranch_sup,<0.1502.0>]
    message_queue_len: 0
    messages: []
    links: [<0.2082.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 1414
  neighbours:

=ERROR REPORT==== 9-Jan-2022::18:08:45.655929 ===
Ranch listener chatterbox_ranch_protocol had connection process started with chatterbox_ranch_protocol:start_link/4 at <0.2102.0> exit with reason: invalid_preface


%%% http2_spec_3_5_SUITE ==> sends_invalid_connection_preface: FAILED
%%% http2_spec_3_5_SUITE ==> {{badmatch,ok},
 [{http2_spec_3_5_SUITE,send_invalid_connection_preface,2,
                        [{file,"/home/runner/work/chatterbox/chatterbox/test/http2_spec_3_5_SUITE.erl"},
                         {line,48}]},
  {http2_spec_3_5_SUITE,sends_invalid_connection_preface,1,
                        [{file,"/home/runner/work/chatterbox/chatterbox/test/http2_spec_3_5_SUITE.erl"},
                         {line,25}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1754}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}
```

**Comment by lixen** [comment] 2022-01-10 16:26
Seems to be this issue https://github.com/tsloughter/chatterbox/pull/6

**Comment by tsloughter** [comment] 2022-05-24 23:35
Looking into this again. I'm hitting the issue with grpcurl and kreya when trying to test a service.

**Closed** 2022-05-24 23:45 UTC

**Comment by tsloughter** [comment] 2022-06-06 15:54
@fenollp yea, mixed up my repos, hehe. I'll get those releases out soon.
